### ISSUE TITLE
there is no way to bidirectionally share data between caches running on in-memory backends

### ISSUE THREAD

**Issue by yomimono** [yomimono/irmin-arp#4]
Currently my best thought on tackling this is taking a list of remote stores at `connect` time, which the store can attempt to call `Irmin.pull` on when a query would otherwise emit a probe.  This has obvious problems if the "remote store" is really network-remote.

**Comment by samoht** [comment]
Do you want to share in-memory backends between different Irmin programs? Maybe you can pull/push between the instances? Or it would be easier to use an on-disk backend.

**Comment by yomimono** [comment]
There's a `push` mechanism already; my best thought so far on implementing this was to add a `pull` mechanism as well.  For an on-disk we can indeed just drop some stuff in, and no such contortions are necessary -- the tests currently (ab?)use this functionality to pre-seed an ARP cache.

**Comment by samoht** [comment]
pulling should work fine then. Please report at the appropriate place if you have an issue :-)
